import{i as m,S as f}from"./assets/vendor-5b791d57.js";(function(){const e=document.createElement("link").relList;if(e&&e.supports&&e.supports("modulepreload"))return;for(const r of document.querySelectorAll('link[rel="modulepreload"]'))c(r);new MutationObserver(r=>{for(const o of r)if(o.type==="childList")for(const i of o.addedNodes)i.tagName==="LINK"&&i.rel==="modulepreload"&&c(i)}).observe(document,{childList:!0,subtree:!0});function p(r){const o={};return r.integrity&&(o.integrity=r.integrity),r.referrerPolicy&&(o.referrerPolicy=r.referrerPolicy),r.crossOrigin==="use-credentials"?o.credentials="include":r.crossOrigin==="anonymous"?o.credentials="omit":o.credentials="same-origin",o}function c(r){if(r.ep)return;r.ep=!0;const o=p(r);fetch(r.href,o)}})();const y="42127236-8bfdbbfbeed8a2dadaca720e8",h="https://pixabay.com/api/";class g{constructor(){this.userQuery="",this.page=1}async fetchArticles(){const e=await axios.get(`${h}?key=${y}&q=${this.userQuery}&image_type=photo&orientation=horizontal&safesearch=true&page=${this.page}&per_page=15`);return this.incrementPage(),e.data}incrementPage(){this.page+=1}resetPage(){this.page=1}get query(){return this.userQuery}set query(e){this.userQuery=e}}document.querySelector(".search-input");const l=document.querySelector(".search-form"),a=document.querySelector(".gallery");document.querySelector("div");const s=document.querySelector('[data-action="load-more"]'),n=new g,L=()=>{const t=document.createElement("span");t.classList.add("loader"),s.append(t)},u=()=>{const t=document.querySelector(".loader");t&&t.remove()};l.addEventListener("submit",b);s.addEventListener("click",S);function b(t){L(),a.innerHTML="",t.preventDefault(),q(),n.userQuery=t.currentTarget.elements.searchQuery.value,n.userQuery.trim()===""&&(m.error({message:"Sorry, there are no images matching your search query. Please try again!",position:"topLeft",transitionIn:"fadeInLeft"}),u()),v(),n.resetPage(),n.fetchArticles().then(function(e){d(e)})}function S(){n.fetchArticles().then(function(t){d(t)})}function v(){s.classList.remove("is-hidden")}function w(t){return t.hits.map(e=>`
            <li class="gallery-item"><a href="${e.largeImageURL}">
          <img class="gallery-image" src="${e.webformatURL}" alt="${e.tags}"></a>
          <p>Likes: ${e.likes}</p>
          <p>Views: ${e.views}</p>
          <p>Comments: ${e.comments}</p>
          <p>Downloads: ${e.downloads}</p>
          </li>`).join("")}function d(t){a.insertAdjacentHTML("beforeend",w(t));const e=new f(".gallery a",P);e.on("show.simplelightbox"),e.refresh(),l.reset(),u()}function q(){a.innerHTML=""}const P={captions:!0,captionType:"attr",captionsData:"alt",captionPosition:"bottom",captionSelector:"img",captionDelay:250};
//# sourceMappingURL=commonHelpers.js.map
