import{i as d}from"./assets/vendor-bee2f3af.js";(function(){const e=document.createElement("link").relList;if(e&&e.supports&&e.supports("modulepreload"))return;for(const r of document.querySelectorAll('link[rel="modulepreload"]'))s(r);new MutationObserver(r=>{for(const o of r)if(o.type==="childList")for(const a of o.addedNodes)a.tagName==="LINK"&&a.rel==="modulepreload"&&s(a)}).observe(document,{childList:!0,subtree:!0});function l(r){const o={};return r.integrity&&(o.integrity=r.integrity),r.referrerPolicy&&(o.referrerPolicy=r.referrerPolicy),r.crossOrigin==="use-credentials"?o.credentials="include":r.crossOrigin==="anonymous"?o.credentials="omit":o.credentials="same-origin",o}function s(r){if(r.ep)return;r.ep=!0;const o=l(r);fetch(r.href,o)}})();const f="42127236-8bfdbbfbeed8a2dadaca720e8",m="https://pixabay.com/api/";class p{constructor(){this.userQuery="",this.page=1}async fetchArticles(){const e=await axios.get(`${m}?key=${f}&q=${this.userQuery}&image_type=photo&orientation=horizontal&safesearch=true&page=${this.page}&per_page=15`);return this.incrementPage(),e.data}incrementPage(){this.page+=1}resetPage(){this.page=1}get query(){return this.userQuery}set query(e){this.userQuery=e}}document.querySelector(".search-input");const y=document.querySelector(".search-form"),i=document.querySelector(".gallery");document.querySelector("div");const c=document.querySelector('[data-action="load-more"]'),n=new p,g=()=>{const t=document.createElement("span");t.classList.add("loader"),c.append(t)},h=()=>{const t=document.querySelector(".loader");t&&t.remove()};y.addEventListener("submit",L);c.addEventListener("click",S);function L(t){g(),i.innerHTML="",t.preventDefault(),q(),n.userQuery=t.currentTarget.elements.searchQuery.value,n.userQuery.trim()===""&&(d.error({message:"Sorry, there are no images matching your search query. Please try again!",position:"topLeft",transitionIn:"fadeInLeft"}),h()),n.resetPage(),n.fetchArticles().then(function(e){u(e)})}function S(){n.fetchArticles().then(function(t){u(t)})}function b(t){return t.hits.map(e=>`
            <li class="gallery-item"><a href="${e.largeImageURL}">
          <img class="gallery-image" src="${e.webformatURL}" alt="${e.tags}"></a>
          <p>Likes: ${e.likes}</p>
          <p>Views: ${e.views}</p>
          <p>Comments: ${e.comments}</p>
          <p>Downloads: ${e.downloads}</p>
          </li>`).join("")}function u(t){i.insertAdjacentHTML("beforeend",b(t))}function q(){i.innerHTML=""}
//# sourceMappingURL=commonHelpers.js.map
